from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_guncelleEkrani(object):
    def setupUi(self, guncelleEkrani):
        guncelleEkrani.setObjectName("guncelleEkrani")
        guncelleEkrani.resize(370, 305)
        guncelleEkrani.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(guncelleEkrani)
        self.label.setGeometry(QtCore.QRect(130, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color:rgb(185, 185, 185);font-size:13pt")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(guncelleEkrani)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(185, 185, 185);font-size:9pt")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(guncelleEkrani)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(185, 185, 185);font-size:9pt")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(guncelleEkrani)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(185, 185, 185);font-size:9pt")
        self.label_4.setObjectName("label_4")
        self.guncelleOnaylaButton = QtWidgets.QPushButton(guncelleEkrani)
        self.guncelleOnaylaButton.setGeometry(QtCore.QRect(320, 250, 32, 32))
        self.guncelleOnaylaButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/onayla.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.guncelleOnaylaButton.setIcon(icon)
        self.guncelleOnaylaButton.setIconSize(QtCore.QSize(32, 32))
        self.guncelleOnaylaButton.setFlat(True)
        self.guncelleOnaylaButton.setObjectName("guncelleOnaylaButton")
        self.guncelleGeriButton = QtWidgets.QPushButton(guncelleEkrani)
        self.guncelleGeriButton.setGeometry(QtCore.QRect(260, 250, 32, 32))
        self.guncelleGeriButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/geri.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.guncelleGeriButton.setIcon(icon1)
        self.guncelleGeriButton.setIconSize(QtCore.QSize(32, 32))
        self.guncelleGeriButton.setFlat(True)
        self.guncelleGeriButton.setObjectName("guncelleGeriButton")
        self.guncelleIDTextBox = QtWidgets.QLineEdit(guncelleEkrani)
        self.guncelleIDTextBox.setGeometry(QtCore.QRect(110, 100, 113, 20))
        self.guncelleIDTextBox.setStyleSheet("color:rgb(185, 185, 185);")
        self.guncelleIDTextBox.setReadOnly(True)
        self.guncelleIDTextBox.setObjectName("guncelleIDTextBox")
        self.guncelleUygulamaTextBox = QtWidgets.QLineEdit(guncelleEkrani)
        self.guncelleUygulamaTextBox.setGeometry(QtCore.QRect(110, 140, 113, 20))
        self.guncelleUygulamaTextBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.guncelleUygulamaTextBox.setObjectName("guncelleUygulamaTextBox")
        self.guncelleSifreTextBox = QtWidgets.QLineEdit(guncelleEkrani)
        self.guncelleSifreTextBox.setGeometry(QtCore.QRect(110, 180, 113, 20))
        self.guncelleSifreTextBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.guncelleSifreTextBox.setEchoMode(QtWidgets.QLineEdit.Password)
        self.guncelleSifreTextBox.setObjectName("guncelleSifreTextBox")

        self.retranslateUi(guncelleEkrani)
        QtCore.QMetaObject.connectSlotsByName(guncelleEkrani)

    def retranslateUi(self, guncelleEkrani):
        _translate = QtCore.QCoreApplication.translate
        guncelleEkrani.setWindowTitle(_translate("guncelleEkrani", "Düzenle"))
        self.label.setText(_translate("guncelleEkrani", "Düzenle"))
        self.label_2.setText(_translate("guncelleEkrani", "ID:"))
        self.label_3.setText(_translate("guncelleEkrani", "Uygulama:"))
        self.label_4.setText(_translate("guncelleEkrani", "Şifre:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    guncelleEkrani = QtWidgets.QWidget()
    ui = Ui_guncelleEkrani()
    ui.setupUi(guncelleEkrani)
    guncelleEkrani.show()
    sys.exit(app.exec_())
