from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kayitEkrani(object):
    def setupUi(self, kayitEkrani):
        kayitEkrani.setObjectName("kayitEkrani")
        kayitEkrani.resize(370, 305)
        kayitEkrani.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(kayitEkrani)
        self.label.setGeometry(QtCore.QRect(30, 90, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(185, 185, 185);font-size:13pt")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(kayitEkrani)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 77, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(185, 185, 185);font-size:13pt")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(kayitEkrani)
        self.label_3.setGeometry(QtCore.QRect(110, 20, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(185, 185, 185);font-size:13pt")
        self.label_3.setObjectName("label_3")
        self.yeniKayitUygulamaAdiTextBox = QtWidgets.QLineEdit(kayitEkrani)
        self.yeniKayitUygulamaAdiTextBox.setGeometry(QtCore.QRect(180, 90, 144, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.yeniKayitUygulamaAdiTextBox.setFont(font)
        self.yeniKayitUygulamaAdiTextBox.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.yeniKayitUygulamaAdiTextBox.setInputMask("")
        self.yeniKayitUygulamaAdiTextBox.setMaxLength(13)
        self.yeniKayitUygulamaAdiTextBox.setFrame(True)
        self.yeniKayitUygulamaAdiTextBox.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.yeniKayitUygulamaAdiTextBox.setObjectName("yeniKayitUygulamaAdiTextBox")
        self.yeniKayitSifreTextBox = QtWidgets.QLineEdit(kayitEkrani)
        self.yeniKayitSifreTextBox.setGeometry(QtCore.QRect(180, 150, 144, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.yeniKayitSifreTextBox.setFont(font)
        self.yeniKayitSifreTextBox.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.yeniKayitSifreTextBox.setInputMask("")
        self.yeniKayitSifreTextBox.setMaxLength(13)
        self.yeniKayitSifreTextBox.setFrame(True)
        self.yeniKayitSifreTextBox.setEchoMode(QtWidgets.QLineEdit.Password)
        self.yeniKayitSifreTextBox.setObjectName("yeniKayitSifreTextBox")
        self.yeniKayitOnaylaButton = QtWidgets.QPushButton(kayitEkrani)
        self.yeniKayitOnaylaButton.setGeometry(QtCore.QRect(320, 260, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yeniKayitOnaylaButton.sizePolicy().hasHeightForWidth())
        self.yeniKayitOnaylaButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.yeniKayitOnaylaButton.setFont(font)
        self.yeniKayitOnaylaButton.setAutoFillBackground(False)
        self.yeniKayitOnaylaButton.setStyleSheet("")
        self.yeniKayitOnaylaButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/onayla.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yeniKayitOnaylaButton.setIcon(icon)
        self.yeniKayitOnaylaButton.setIconSize(QtCore.QSize(32, 32))
        self.yeniKayitOnaylaButton.setFlat(True)
        self.yeniKayitOnaylaButton.setObjectName("yeniKayitOnaylaButton")
        self.yeniKayitGeriButton = QtWidgets.QPushButton(kayitEkrani)
        self.yeniKayitGeriButton.setGeometry(QtCore.QRect(260, 260, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yeniKayitGeriButton.sizePolicy().hasHeightForWidth())
        self.yeniKayitGeriButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.yeniKayitGeriButton.setFont(font)
        self.yeniKayitGeriButton.setAutoFillBackground(False)
        self.yeniKayitGeriButton.setStyleSheet("")
        self.yeniKayitGeriButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/geri.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yeniKayitGeriButton.setIcon(icon1)
        self.yeniKayitGeriButton.setIconSize(QtCore.QSize(32, 32))
        self.yeniKayitGeriButton.setFlat(True)
        self.yeniKayitGeriButton.setObjectName("yeniKayitGeriButton")

        self.retranslateUi(kayitEkrani)
        QtCore.QMetaObject.connectSlotsByName(kayitEkrani)

    def retranslateUi(self, kayitEkrani):
        _translate = QtCore.QCoreApplication.translate
        kayitEkrani.setWindowTitle(_translate("kayitEkrani", "Yeni Kayit"))
        self.label.setText(_translate("kayitEkrani", "Uygulama Adı:"))
        self.label_2.setText(_translate("kayitEkrani", "Şifre:"))
        self.label_3.setText(_translate("kayitEkrani", "Yeni Kayit Ekle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kayitEkrani = QtWidgets.QWidget()
    ui = Ui_kayitEkrani()
    ui.setupUi(kayitEkrani)
    kayitEkrani.show()
    sys.exit(app.exec_())
